import test from 'node:test';
import assert from 'node:assert/strict';
import {ExperienceState,classifyOccupancy,scaleFromTarget} from '../site/v3/tracking.js';
test('empty card never starts',()=>{const s=new ExperienceState();for(let t=0;t<3000;t+=150){s.image(t);s.evidence(false,t);assert.equal(s.tick(t).visible,false);}});
test('persistent broad tube evidence starts without a click',()=>{const s=new ExperienceState();for(let t=0;t<=600;t+=150){s.image(t);s.evidence(true,t);s.tick(t);}assert.equal(s.tick(610).visible,true);});
test('brief evidence loss retains timeline; extended removal stops',()=>{const s=new ExperienceState();for(let t=0;t<=750;t+=150){s.image(t);s.evidence(true,t);s.tick(t);}s.image(1200);s.evidence(false,1200);assert.equal(s.tick(1200).visible,true);s.image(2600);s.evidence(false,2600);assert.equal(s.tick(2600).visible,false);});
test('lost image hides untracked scene without restarting its timeline',()=>{const s=new ExperienceState();for(let t=0;t<=600;t+=150){s.image(t);s.evidence(true,t);s.tick(t);}const before=s.progressMs;s.lost();assert.equal(s.tick(750).visible,false);s.image(850);s.evidence(true,850);assert.equal(s.tick(850).visible,true);assert.ok(s.progressMs>=before);});
test('missing or tiny occupancy is rejected',()=>{const rows=Array.from({length:33},(_,i)=>({y:-120+i*6,valid:9,dark:0}));assert.equal(classifyOccupancy(rows).present,false);rows.slice(2,6).forEach(r=>r.dark=8);assert.equal(classifyOccupancy(rows).present,false);assert.equal(classifyOccupancy(rows.slice(0,4)).present,false);});
test('separated dark tube ends with a light label are accepted',()=>{const rows=Array.from({length:33},(_,i)=>({y:-120+i*6,valid:9,dark:i<7||i>25?7:0}));assert.equal(classifyOccupancy(rows).present,true);});
test('physical scale rejects malformed tracking events',()=>{assert.equal(scaleFromTarget({scale:1,scaledWidth:1.8}),.01);assert.equal(scaleFromTarget({}),null);});
